### ISSUE TITLE
Tests Fail Sporadically

### ISSUE THREAD

**Issue by Kortanul** [WrenSecurity/wrenicf-java-framework#4]
## Versions Affected
1.5.2.0

## Steps to Reproduce
1. Checkout the project on the `sustaining/1.5.2.0` branch.
2. Run `mvn clean install -Duser.name=Kortanul -Pforgerock-release -Dignore-artifact-sigs` from the root of the project.
3. If there are no failures, repeat step 2 once more.
4. If there are test failures, re-start the build from where it failed via `mvn clean install -Duser.name=Kortanul -Pforgerock-release -Dignore-artifact-sigs -rf FAILING-STEP` (where `FAILING-STEP` is the step that failed, which is typically `:connector-frameowork-internal`).

## Desired
All tests pass.

## Actual
Some tests fail sporadically. When re-run they pass, even without any code changes.

Some example tests that fail sporadically include:
### Failure 1
```
Thread Id: 1    Time: 2018-03-11 13:52:07.141   Class: org.identityconnectors.framework.impl.test.TestHelpersImpl       Method: fillConfiguration(TestHelpersImpl.java:147)     Level: WARN     Message: Configuration property foo does not exist!
Tests run: 469, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 168.836 sec <<< FAILURE! - in TestSuite
testBatchUseCase3(org.identityconnectors.framework.impl.api.LocalConnectorInfoManagerTests)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
        at org.identityconnectors.framework.impl.api.LocalConnectorInfoManagerTests.testBatchUseCase3(LocalConnectorInfoManagerTests.java:323)

Results :

Failed tests:
  LocalConnectorInfoManagerTests.testBatchUseCase3:323 expected [0] but found [1]
  
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project connector-framework-internal: There are test failures.
```

**Comment by pavelhoral** [comment]
I thought that this is connected to the timeouts being too short, but I am more and more convinced it is some sort of locking race condition because I am not able to reproduce this with cgroups (limiting cpu cores or cpu time) or when running surefire:test on a single failing module.

**Comment by pavelhoral** [comment]
Getting pretty stable failures with ` mvn surefire:test -pl framework-rpc`:

```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.394 s <<< FAILURE! - in TestSuite
[ERROR] org.forgerock.openicf.common.rpc.RequestDistributorTest.testSimpleRequest  Time elapsed: 0.006 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.forgerock.openicf.common.rpc.RequestDistributorTest.testSimpleRequest(RequestDistributorTest.java:148)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   RequestDistributorTest.testSimpleRequest:148 expected [true] but found [false]
[INFO] 
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
```

The RPC module is pretty complex and I am not sure why all the complexity is necessary. There are only 11 source files in that module but I feel like my head will explode while trying to understand all intentions and relations behind those components :/.

**Comment by pavelhoral** [comment]
I really don't understand why the RPC part of ICF is so so sooo complex :(. The issue from previous comment is really a race condition between `RemoteRequestGroup` cleanup performed in executor service thread and test assertion being performed in main thread:

* This is run by thread from thread pool after completing the request https://github.com/WrenSecurity/wrenicf-java-framework/blob/17fedf9a46c36edf39939c72a1bba5626b89f7aa/framework-rpc/src/main/java/org/forgerock/openicf/common/rpc/RemoteConnectionGroup.java#L172
* This is run in main thread https://github.com/WrenSecurity/wrenicf-java-framework/blob/17fedf9a46c36edf39939c72a1bba5626b89f7aa/framework-rpc/src/test/java/org/forgerock/openicf/common/rpc/RequestDistributorTest.java#L148

All assertions based on `getRemoteRequest` property can not work with the current setup. Those requests are cleaned asynchronously after request completion.

**Comment by pavelhoral** [comment]
I have fixed few issues in the code and tests are now green (#26).

However I have to say that I am not very happy with the codebase. It is written in a way that makes it very hard to understand and work with. Also many places seem like race conditions [are about to happen there](https://github.com/WrenSecurity/wrenicf-java-framework/pull/26#issuecomment-1222269148)... and the tests are very messy as well.

So I have one closing thought: Shouldn't we be better of just rewriting the newer stuff?
